# default snippets
# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'
# depends = ['deoplete.nvim']

# snippets
# [[plugins]]
# repo = 'Shougo/neosnippet.vim'
# hook_add = '''
#   " snippets
#   let g:neosnippet#snippets_directory='~/.config/nvim/snippets'
#   " Plugin key-mappings.
#   " Note: It must be "imap" and "smap".  It uses <Plug> mappings.
#   imap <C-k>     <Plug>(neosnippet_expand_or_jump)
#   smap <C-k>     <Plug>(neosnippet_expand_or_jump)
#   xmap <C-k>     <Plug>(neosnippet_expand_target)
#   " SuperTab like snippets behavior.
#   " Note: It must be "imap" and "smap".  It uses <Plug> mappings.
#   "imap <expr><TAB>
#   " \ pumvisible() ? "\<C-n>" :
#   " \ neosnippet#expandable_or_jumpable() ?
#   " \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
#   smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
#   \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
#   inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
#   " For conceal markers.
#   if has('conceal')
#     set conceallevel=2 concealcursor=niv
#   endif
# '''

# "(" ")" color
[[plugins]]
repo = 'https://github.com/luochen1990/rainbow'
hook_add = 'let g:rainbow_active = 1'

# auto input "(" + ")"
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

# gcc > commentout
[[plugins]]
repo = 'https://github.com/tyru/caw.vim'

# resize splited window
[[plugins]]
repo = 'https://github.com/simeji/winresizer'
hook_add = '''
  "window resize
  let g:winresizer_vert_resize = 1
  let g:winresizer_horiz_resize = 1 '''

#use esc > no ja
[[plugins]]
repo = 'vim-scripts/fcitx.vim'

# usitapunikiakun
[[plugins]]
repo = 'https://github.com/Inazuma110/ushitapunikiakun.vim.git'
hook_add = 'let g:ushitapunikiakun#insert_str = " "'

#vim-devicons
[[plugins]]
repo = 'ryanoasis/vim-devicons'

#vim-airline
[[plugins]]
repo = 'https://github.com/vim-airline/vim-airline.git'
hook_add = '''
  let g:airline_theme = "luna"
  let g:airline_powerline_fonts = 1
  let g:airline#extensions#tabline#enabled = 1
  '''

#vim-airline-theme
[[plugins]]
repo = 'https://github.com/vim-airline/vim-airline-themes.git'
#html-css
[[plugins]]
repo = 'https://github.com/mattn/emmet-vim.git'
[[plugins]]
repo = 'https://github.com/tpope/vim-surround.git'
[[plugins]]
repo = 'https://github.com/tyru/open-browser.vim.git'
[[plugins]]
repo = 'https://github.com/hail2u/vim-css3-syntax.git'
[[plugins]]
repo = 'https://github.com/pangloss/vim-javascript.git'
[[plugins]]
repo = 'https://github.com/kchmck/vim-coffee-script.git'
#indentLine
[[plugins]]
repo = 'https://github.com/Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_color_term =239
  let g:indentLine_color_gui = '#708090'
  let g:indentLine_char = '|'
'''

