# default snippets
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
depends = ['deoplete.nvim']

# snippets
[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
  " snippets
  let g:neosnippet#snippets_directory='~/.config/nvim/snippets'
  " Plugin key-mappings.
  " Note: It must be "imap" and "smap".  It uses <Plug> mappings.
  imap <C-k>     <Plug>(neosnippet_expand_or_jump)
  smap <C-k>     <Plug>(neosnippet_expand_or_jump)
  xmap <C-k>     <Plug>(neosnippet_expand_target)
  " SuperTab like snippets behavior.
  " Note: It must be "imap" and "smap".  It uses <Plug> mappings.
  "imap <expr><TAB>
  " \ pumvisible() ? "\<C-n>" :
  " \ neosnippet#expandable_or_jumpable() ?
  " \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
  smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
  \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
  inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
  " For conceal markers.
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''

# complete
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_refresh_always = 0
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
  \ neosnippet#expandable_or_jumpable() ?
  \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1

[[plugins]]
repo = 'https://github.com/cespare/vim-toml'

[[plugins]]
repo = 'https://github.com/itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
      \ 'colorscheme': 'wombat'
      \ }
'''

[[plugins]]
repo = 'https://github.com/tyru/caw.vim'
[[plugins]]

repo = 'https://github.com/luochen1990/rainbow'
hook_add = 'let g:rainbow_active = 1'

[[plugins]]
repo = 'https://github.com/thinca/vim-quickrun'

[[plugins]]
repo = 'https://github.com/simeji/winresizer'
hook_add = '''
  "window resize
  let g:winresizer_vert_resize = 1
  let g:winresizer_horiz_resize = 1 '''
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1
[[plugins]]
repo = 'https://github.com/Shougo/neco-syntax'
[[Plugins]]
repo = 'https://github.com/deoplete-plugins/deoplete-jedi'

[[plugins]]
repo = 'zchee/deoplete-jedi'
#on_i = 1
on_ft = 'python'


#use esc > no ja
[[plugins]]
repo = 'vim-scripts/fcitx.vim'


#previm
[[plugins]]
repo = 'https://github.com/previm/previm.git'

#open-browser
[[Plugins]]
repo = 'https://github.com/tyru/open-browser.vim.git'

#neoinclude
[[plugins]]
repo = 'https://github.com/Shougo/neoinclude.vim.git'

#latex_auto_compile
repo = 'lervag/vimtex'
hook_add = '''
  "部分的にコンパイルする設定
  function! s:previewTex() range
  let l:tmp = @@
  silent normal gvy
  let l:selected = split(@@, "\n")
  let @@ = l:tmp

  " \"\\documentclass{tADR2e}",
  "" let l:template1 = ["\\documentclass[a4paper]{jsarticle}",
  " \"\\usepackage[dvipdfmx]{graphicx}",
  " \"\\usepackage{amsmath,amssymb,bm}",
  " \"\\pagestyle{empty}",
  let l:template1 = ["\\documentclass{tADR2e}",
  \"\\begin{document}"]
  let l:template2 = ["\\end{document}"]

  let l:output_file = "preview.tex"
  call writefile(extend(extend(l:template1, l:selected), template2), l:output_file)
  call system("latexmk preview.tex")
  call system("mupdf preview.pdf")
  endfunction
  autocmd FileType tex
  \ | vnoremap <buffer> <localleader>la :call <SID>previewTex()<CR>'''
